<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>LanTransfer.Storage</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LanTransfer.Common\LanTransfer.Common.csproj" />
    <ProjectReference Include="..\LanTransfer.Core\LanTransfer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>

</Project>
